
mods:
    - name: 'AutoDeconstruct'
    - name: 'Squeak Through'
    - name: 'Todo-List'
    - name: 'Bottleneck'
    - name: 'Warehousing'
    - name: 'Robocharger'
    - name: 'bobassembly'
    - name: 'bobelectronics'
    - name: 'bobenemies'
    - name: 'bobequipment'
    - name: 'bobgreenhouse'
    - name: 'bobinserters'
    - name: 'boblibrary'
    - name: 'boblogistics'
    - name: 'bobmining'
    - name: 'bobmodules'
    - name: 'bobores'
    - name: 'bobplates'
    - name: 'bobpower'
    - name: 'bobrevamp'
    - name: 'bobvehicleequipment'
    - name: 'bobtech'
    - name: 'bobwarfare'
