mods:
    - name: 'AutoDeconstruct'
    - name: 'Squeak Through'
    - name: 'Todo-List'
    - name: 'Bottleneck'
    - name: 'Warehousing'
    - name: 'Robocharger'
    - name: 'kry-inserters'
    - name: 'helmod' # https://mods.factorio.com/mod/helmod
