mods:
    - name: "AutoDeconstruct"
    - name: "Squeak Through"
    - name: "Todo-List"
    - name: "Bottleneck"
    - name: "Warehousing"
    - name: "Robocharger"
    - name: "kry-inserters"
    - name: "helmod" # https://mods.factorio.com/mod/helmod
    - name: "Side Inserters" # https://mods.factorio.com/mod/Side%20Inserters
    - name: "YARM" # https://mods.factorio.com/mod/YARM
    - name: "graftorio" # https://mods.factorio.com/mod/graftorio
